version: '3.7'
services:
  db:
    image: postgres
    restart: always
    container_name: web-db
    environment:
      - POSTGRES_PASSWORD=gui10tare
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGUSER = postgres
    ports:
      - 5432:5432
  web:
    build:
      context: ./back/
      dockerfile: Dockerfile
    # entrypoint: "entrypoint.sh"
    # command: gunicorn back.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web-backend
    environment:
      - SUPERUSER_PASSWORD=gui10tare
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000