services:
  db:
    image: postgres
    restart: always
    container_name: web-db
    environment:
      - POSTGRES_PASSWORD=gui10tare
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGUSER = postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5 
    ports:
      - 5432:5432
  web:
    build:
      context: ./back/
      dockerfile: Dockerfile
    # entrypoint: "entrypoint.sh"
    command: gunicorn back.wsgi:application --bind 0.0.0.0:8000
    container_name: web-backend
    restart: always
    depends_on:
      db:
        condition: "service_healthy"
    ports:
      - 8000:8000